# Generated by Django 3.2.7 on 2021-09-03 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_jo', models.CharField(blank=True, max_length=20, verbose_name='NOMOR JO')),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keterangan')),
                ('jumlah_Ac', models.PositiveIntegerField()),
                ('tgl_input', models.DateField(auto_now=True)),
                ('slugJO', models.SlugField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientJO', to='client.clientmodel')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productJO', to='product.productmodel')),
            ],
            options={
                'verbose_name': 'Job Order',
                'verbose_name_plural': 'Job Order',
            },
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice', models.CharField(max_length=20, verbose_name='Nomor Invoice')),
                ('statusPembayaran', models.CharField(choices=[('LUNAS', 'LUNAS'), ('BELUM', 'BELUM LUNAS')], default='BELUM', max_length=20)),
                ('Keterangan', models.TextField()),
                ('tanggal', models.DateField(auto_now=True, verbose_name='Tanggal')),
                ('totalInvoice', models.PositiveIntegerField(default=0, verbose_name='Total Pembayaran')),
                ('slug_Invoice', models.SlugField()),
                ('clientINV', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='InvoiceClient', to='client.clientmodel', verbose_name='Invoice Client')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='approvalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.BooleanField(default=False)),
                ('tgl_approve', models.DateField(auto_now=True, null=True, verbose_name='Tanggal Approval')),
                ('slug_Approv', models.SlugField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='adminUser', to=settings.AUTH_USER_MODEL)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientApprov', to='client.clientmodel')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ApprovPesanan', to='pesanan.invoicemodel')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approval Pesanan',
            },
        ),
    ]
