# Generated by Django 3.1.1 on 2021-07-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventContent', '0002_auto_20210721_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontentmodel',
            name='slug_Content',
            field=models.SlugField(),
        ),
    ]
