# Generated by Django 3.1.1 on 2021-07-05 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pesanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pembayaranModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pembayaran', models.CharField(max_length=30, verbose_name='Nomor Pembayaran')),
                ('tgl_input', models.DateField(auto_now=True, verbose_name='Tanggal Input')),
                ('jumlah', models.PositiveIntegerField(default=0, verbose_name='Jumlah Pembayaran')),
                ('keterangan', models.TextField()),
                ('tgl_pembayaran', models.DateField(verbose_name='Tanggal Pembayaran')),
                ('slug_pembayaran', models.SlugField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='pesanan.invoicemodel')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
            },
        ),
    ]
