# Generated by Django 3.1.1 on 2021-07-05 04:10

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('jabatan', models.CharField(choices=[('ADMIN', 'ADMIN'), ('TEKNISI', 'TEKNISI')], max_length=8)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Username',
                'verbose_name_plural': 'Username',
            },
            managers=[
                ('objects', account.models.AccountManage()),
            ],
        ),
    ]
