# Generated by Django 3.1.1 on 2021-07-05 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pesanan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPKModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_SPK', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Nomor SPK')),
                ('tgl_input', models.DateField(auto_now=True, verbose_name='Tanggal Input')),
                ('tgl_pengerjaan', models.DateField(verbose_name='Tanggal Pengerjaan')),
                ('keterangan', models.TextField(verbose_name='Keterangan')),
                ('status', models.CharField(choices=[('PENDING', 'ON PROGRESS'), ('CANCEL', 'CANCEL'), ('SELESAI', 'SELESAI')], default='PENDING', max_length=10)),
                ('slug_SPK', models.SlugField()),
                ('pesanan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SPK', to='pesanan.invoicemodel', verbose_name='Invoice')),
                ('teknisi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teknisiUser', to=settings.AUTH_USER_MODEL, verbose_name='Teknisi')),
            ],
            options={
                'verbose_name': 'Surat Perintah Kerja',
                'verbose_name_plural': 'Surat Perintah Kerja',
            },
        ),
    ]
