# Generated by Django 3.2.7 on 2021-09-03 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SPK_teknisi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pesanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spkmodel',
            name='pesanan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SPK', to='pesanan.invoicemodel', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='spkmodel',
            name='teknisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teknisiUser', to=settings.AUTH_USER_MODEL, verbose_name='Teknisi'),
        ),
    ]
