# Generated by Django 3.2.7 on 2021-09-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaProduct', models.CharField(max_length=30)),
                ('keteranganProduct', models.TextField()),
                ('hargaProduct', models.PositiveIntegerField()),
                ('slugProduct', models.SlugField(editable=False)),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
